[bans]
deny = [
  "aws-lc",
  "aws-lc-rs",
  "aws-lc-sys",
  "native-tls",
  "openssl",
]
multiple-versions = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Zlib",
  "Unicode-3.0",
  "Unlicense",
]

[[licenses.clarify]]
expression = "MIT AND ISC AND OpenSSL"
name = "ring"

[[licenses.clarify.license-files]]
hash = 3171872035
path = "LICENSE"

[advisories]
ignore = [
  "RUSTSEC-2023-0089", # unmainatined: postcard -> heapless -> atomic-polyfill
]

[sources]
allow-git = [
  "https://github.com/n0-computer/iroh"
]
